import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // add weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "QuickShare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans antialiased min-h-screen flex items-center justify-center min-h-screen bg-gradient-to-br from-purple-400 via-purple-500 to-blue-500 relative overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
